name: Build DriveMaster Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Corrected path to requirements.txt
        pip install -r projects/DriveMaster/requirements.txt

    - name: Build executable with PyInstaller
      run: |
        # Corrected path to main.spec
        python -m PyInstaller projects/DriveMaster/main.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DriveMaster-Executable
        # Corrected path to the final executable
        path: projects/DriveMaster/dist/main.exe

